from __future__ import annotations
from pathlib import Path
from typing import Protocol

class FileOpsPort(Protocol):
    def move(self, src: Path, dst: Path) -> Path: ...
    def exists(self, p: Path) -> bool: ...
    def mkdirs(self, p: Path) -> None: ...
