"""person name to display_name

Revision ID: b220f98a4489
Revises: 31f944c962f3
Create Date: 2025-10-02 12:57:25.395531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b220f98a4489'
down_revision: Union[str, Sequence[str], None] = '31f944c962f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_parent'), table_name='tag', schema='hexmedia')
    op.drop_constraint(op.f('fk_tag_parent_id_tag'), 'tag', schema='hexmedia', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tag_parent_id_tag'), 'tag', 'tag', ['parent_id'], ['id'], source_schema='hexmedia', referent_schema='hexmedia', ondelete='SET NULL')
    op.drop_index(op.f('ix_tag_group_depth'), table_name='tag_group', schema='hexmedia')
    op.drop_index(op.f('ix_tag_group_parent_key'), table_name='tag_group', schema='hexmedia')
    op.drop_index(op.f('ix_tag_group_path'), table_name='tag_group', schema='hexmedia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_group_path'), 'tag_group', ['path'], unique=False, schema='hexmedia')
    op.create_index(op.f('ix_tag_group_parent_key'), 'tag_group', ['parent_id', 'key'], unique=False, schema='hexmedia')
    op.create_index(op.f('ix_tag_group_depth'), 'tag_group', ['depth'], unique=False, schema='hexmedia')
    op.drop_constraint(op.f('fk_tag_parent_id_tag'), 'tag', schema='hexmedia', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tag_parent_id_tag'), 'tag', 'tag', ['parent_id'], ['id'], source_schema='hexmedia', referent_schema='hexmedia', ondelete='RESTRICT')
    op.create_index(op.f('ix_tag_parent'), 'tag', ['parent_id'], unique=False, schema='hexmedia')
    # ### end Alembic commands ###
